CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
OLED_ENABLE = yes
JOYSTICK_ENABLE = yes
RAW_ENABLE = yes

# optimizations
LTO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
NO_DEBUG = yes
NO_PRINT = yes
